ProtocolConfiguration:
  Magic: 1977739567
  MaxTraceableBlocks: 200000
  TimePerBlock: 1s
  MemPoolSize: 50000
  StandbyCommittee:
    - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
  ValidatorsCount: 1
  SeedList:
    - node_single:20333
  VerifyTransactions: true
  P2PSigExtensions: false

ApplicationConfiguration:
  SkipBlockVerification: false
  DBConfiguration:
    Type: "rocksdb" # options: 'leveldb' 'inmemory','boltdb', 'badgerdb', 'pebbledb', 'rocksdb'
    LevelDBOptions:
      DataDirectoryPath: "chains/single/r1"
    
  P2P:
    Addresses:
      - ":20333" # in form of "[host]:[port][:announcedPort]"
    DialTimeout: 3s
    ProtoTickInterval: 2s
    PingInterval: 30s
    PingTimeout: 90s
    MaxPeers: 10
    AttemptConnPeers: 5
    MinPeers: 0
  Relay: true
  Oracle:
    Enabled: false
    AllowedContentTypes:
      - application/json
    Nodes:
      - http://node_single:50012
    RequestTimeout: 5s
    UnlockWallet:
      Path: "./wallet.json"
      Password: "one"
  RPC:
    Enabled: true
    Addresses:
      - ":50012"
    EnableCORSWorkaround: true
    MaxGasInvoke: 15
    SessionEnabled: true
  Prometheus:
    Enabled: true
    Addresses:
      - ":20001"
  Consensus:
    Enabled: true
    UnlockWallet:
      Path: "./wallet.json"
      Password: "one"
